adyen-mock:
  webhooks.hmac-key: 53D73140BB57D4799ED9DB5E83AA658093D46A5BDBAE9182BAC9DE573B04C40C

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/adyenmock
    username: adyen
    password: adyen_dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.yaml

webhook:
  base-interval: 60
  retries:
    max-attempts: 3
    interval: 30
