spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/adyenmock
    username: adyen
    password: adyen_dev
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate.dialect: org.hibernate.dialect.MariaDBDialect
  liquibase:
    change-log: classpath:/liquibase/db.changelog-master.yaml
    
    